# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82abdb204e34822a21046f638f7d7ca16f518006fe81d38c41d790e9a71270decfc5fb5720c280dadfdc06283d03cb02a3dc4aa904dacad176e3f031f2778045

test:
  secret_key_base: 260f0d8d1ce1b0f87fd0d35deb541be16d54e9338b72e39a2bfbcc01352aba96b4d00db3a91e7c45218eb7a674688dd09d1e2ad613398c5489b8569241ed19ac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
